name: Build and Test Configuration
on:
  workflow_call:
    inputs:
      DOCKER_REPOSITORY:
        required: false
        type: string
        default: ''
      OS:
        required: false
        type: string
      CMAKE_BUILD_TYPE:
        required: false
        type: string
      BUILD_AND_TEST_ARGS:
        required: false
        type: string
      ENABLE_HYPRE:
        required: false
        type: string
      ENABLE_HYPRE_DEVICE:
        required: false
        type: string
      ENABLE_TRILINOS:
        required: false
        type: string
      GCP_BUCKET:
        required: false
        type: string
      HOST_CONFIG:
        required: false
        type: string
      COMMIT:
        required: false
        type: string
    secrets:
      GOOGLE_CLOUD_GCP:
        required: false
jobs:
  build_and_test:
    runs-on: ${{ inputs.OS }}
    steps:
    - name: Test echo everything
      env:
        DOCKER_REPOSITORY: ${{ inputs.DOCKER_REPOSITORY }}
        CMAKE_BUILD_TYPE: ${{ inputs.CMAKE_BUILD_TYPE }}
        BUILD_AND_TEST_ARGS: ${{ inputs.BUILD_AND_TEST_ARGS }}
        ENABLE_HYPRE: ${{ inputs.ENABLE_HYPRE }}
        ENABLE_HYPRE_DEVICE: ${{ inputs.ENABLE_HYPRE_DEVICE }}
        ENABLE_TRILINOS: ${{ inputs.ENABLE_TRILINOS }}
        GCP_BUCKET: ${{ inputs.GCP_BUCKET }}
        HOST_CONFIG: ${{ inputs.HOST_CONFIG }}
        COMMIT: ${{ inputs.COMMIT }}
      run: |
        echo DOCKER_REPOSITORY is ${DOCKER_REPOSITORY}
        echo CMAKE_BUILD_TYPE is ${CMAKE_BUILD_TYPE}
        echo BUILD_AND_TEST_ARGS is ${BUILD_AND_TEST_ARGS}
        echo HOST_CONFIG is ${HOST_CONFIG}
        echo ENABLE_HYPRE is ${ENABLE_HYPRE} 
        echo ENABLE_HYPRE_DEVICE is ${ENABLE_HYPRE_DEVICE}
        echo ENABLE_TRILINOS is ${ENABLE_TRILINOS}
        echo GCP_BUCKET is ${GCP_BUCKET}
        echo COMMIT is ${COMMIT}
        echo OS is ${OS}