name: hello-world
on: push
  # pull_request:
  #   types:
  #     - opened
  #     - edited
  #     - reopened
  #     - synchronize
  #     - ready_for_review

env:
  GEOSX_TPL_TAG: 203-915

jobs:
  check-submodules:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: false
    - name: run-test-submodule-updated-sh
      # run: "scripts/test_submodule_updated.sh"
      run: "false"
  # code_style:
  #   runs-on: ubuntu-latest
  #   env:
  #   steps:
  build:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    needs: [ check-submodules ]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: false
    - name: my-step
      run: echo "Hello World!"
  # check-that-non-blocking-failure-jobs-succeeded:
  #   runs-on: ubuntu-latest
  #   needs: [ check-submodules, build ]
  #   steps:
  #   - name: Success
  #     run: "true"
