name: hello-world
on: push

env:
  GEOSX_TPL_TAG: 203-915

jobs:
  check-submodules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: false
    - name: run-test-submodule-updated-sh
      run: scripts/test_submodule_updated.sh
  # code_style:
  #   runs-on: ubuntu-latest
  #   env:
  #   steps:
  build:
    #if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: false
    - name: my-step
      run: echo "Hello World!"
  check-that-non-blocking-failure-jobs-succeeded:
    needs: [ check_submodules, build ]
    steps:
    - name: Success
      run: "true"
